version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_fastapi
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  movies_fastapi:
    build: .
    container_name: movies_fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo_data: